# Generated by Django 4.0.3 on 2022-03-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='habita_la_unidad',
        ),
    ]
